Cray-HPE/cfs-operator

kubernetes/cray-cfs-operator/templates/clusterrole.yaml
kubernetes/cray-cfs-operator/templates/clusterrolebinding.yaml

This mod adds a ClusterRole and ClusterRoleBinding to enable the CFS service account access to all of the resources cluster wide (because activities like draining a node are cluster wide).
This change should be fully backwards compatible. 
CASMINST-3572
Tested on Mug, verified that with two files applied a full end-to-end rebuild worked as expected.
Mug
Applied files, ran CFS session, verified results.
No known risk.
- [x ] Version number(s) incremented, if applicable
- [x ] Copyrights updated
- [x ] License file intact
- [x ] Target branch correct
- [x ] CHANGELOG.md updated
- [x ] Testing is appropriate and complete, if applicable
- [x ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

Added ClusterRole and ClusterRoleBinding for NCN lifecycle coordination

---

update_versions.conf

Fixes the annotation for the aee image by adding the file to the update_version.conf
* Resolves CASMCMS-7614
NA - build only
None

CASMCMS-7614: Fix versioning for the aee image annotation

---

README.md

Pull in a new AEE image from the findings in CASMTRIAGE-2853. Backwards compatible.
* Resolves [CASMTRIAGE-2853](issue link)
* Merge after https://github.com/Cray-HPE/ansible-execution-environment/pull/19
See https://github.com/Cray-HPE/ansible-execution-environment/pull/19
See https://github.com/Cray-HPE/ansible-execution-environment/pull/19

CASMTRIAGE-2853: pull in new AEE image

---

kubernetes/cray-cfs-operator/Chart.yaml
kubernetes/cray-cfs-operator/values.yaml

Updates the alpine/git image used to clone in CFS jobs.
* Resolves CASMCMS-7725
* Mug
Updated the configmap and ran a session with the new image successfully.
None
- [S] Target branch correct

CASMCMS-7725: Update alpine/git image to fix CVE

---

src/cray/cfs/operator/events/session_events.py
src/cray/cfs/teardown/__main__.py

This removes the code that copies the ssh keys to /root, since that is no longer possible since these containers no longer run as root.  The one place these ssh keys actually matter is during teardown, so that code has been updated to point at the new source of the keys.
The keys are also still used in the Ansible containers, but the code to copy them to the appropriate location is in the entrypoint for the aee image, and so Ansible containers are unaffected by this change.
* Resolves CASMTRIAGE-2909
* Hela
The changes were deployed and CFS was successfully run against both live nodes and images.
None

CASMTRIAGE-2909: Update teardown to use non-root key source

---

src/cray/cfs/inventory/dynamic.py

Switches to using HSM v2 since v1 is going away.  There were no changes in the data, so only the endpoint has changed.
* Resolves CASMCMS-7447
* Hela
Deployed the change and ran a test session.  Also compared the data from all used endpoints to confirm that there were no changes.
None

CASMCMS-7447: Update to use hsm v2

---

src/cray/cfs/operator/events/session_events.py

During CFS startup of an AEE job, the inventory is contructed exactly once. However, the keys may be provided to the running inventory pod using a number of different bit configurations, depending on the umask as set by the product release (or the user on a worker node), or the default policy modes set by k8s. As a result, we need to explicitly set the permision bits on copied files to be more restrictive. This allows Ansible (and the underlying ssh transport) to always work regardless of what form the secrets arrive in during CFS session launch.

CASMCMS-8029: Mitigate umask issues associated with copying keys

---

CHANGELOG.md
Dockerfile
requirements-dev.txt
requirements-test.txt
requirements.txt
update_external_versions.conf

The 'dev.cray.com' domain is being retired and the servers moved to hpe domains.  This PR removes references to servers on this domain where able, and updates to the new hpe addresses where we still need to reference internal servers.  There are no real code changes - should just be pulling the same packages from different locations.
* Resolves [CASMCMS-7971](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7971)
* `Mug`
The new versions of all services are installed on Mug and are being left in place while Jason does Bos v2 testing to give these a complete workout.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If …

CASMCMS-7971 - update dev.cray.com addresses.

---

CHANGELOG.md
src/cray/cfs/inventory/image/__init__.py
src/cray/cfs/operator/events/session_events.py

Fixes two issues reported by NERSC.
* Fixes container users so to avoid permissions issues caused by having some containers run as root and some as nobody.
* Changes the behavior of image customization to allow additional inventory, and instead use an automatic limit so that nothing targets hosts in the additional inventory.  This allows variables set in the additional inventory to be used.
* Resolves CASMCMS-8120
* Resolves CASMCMS-8121
* Fanta
- Tested image customization with and without additional inventory, before and after these changes.
No

Fixes for using additional inventory with image customization

---

CHANGELOG.md
kubernetes/cray-cfs-operator/values.yaml
src/cray/cfs/operator/events/session_events.py

Escalates the pods to a high priority to improve CFS' ability to run when the system is partially down.
* Resolves CASMTRIAGE-3835
* Mug
Deployed the new image chart and tested basic functions
None

CASMTRIAGE-3835: Escalate pod priority

---

CHANGELOG.md
kubernetes/cray-cfs-operator/templates/configmap.yaml
kubernetes/cray-cfs-operator/values.yaml
src/cray/cfs/inventory/__main__.py
src/cray/cfs/inventory/dynamic.py
src/cray/cfs/inventory/image/__init__.py
src/cray/cfs/logging/__init__.py
src/cray/cfs/operator/__main__.py
src/cray/cfs/operator/cfs/options.py
src/cray/cfs/operator/events/session_events.py
src/cray/cfs/teardown/__main__.py

Contains changes for 
* CASMCMS-7719: Check HSM group names to make sure they are valid Ansible
* CASMCMS-5919: Fix image teardown to mark failed images
* CASMCMS-7820: Add new parameter for naming image customization results
* CASMCMS-7886: Fix exit code when git checkout fails
* CASMCMS-7639: Add pointer to IMS logs when image inventory creation fails
* CASMCMS-8211: Updated the logging level to be controlled by CFS options
* CASMCMS-8208: Make Ansible container limits/requests configurable
* CASMCMS-8243: Add cfs_image host group to image inventory
* Tested on starlord
Generally ran sessions and verified output, changing options and other parameters as needed to test the individual tickets
None

Fixes for several small usability tickets

---

src/cray/cfs/operator/events/session_events.py

Removes the high priority pod class from CFS sessions so that CFS does not interfere with other services during configuration.
* Resolves CASMTRIAGE-4452
* Shandy
- Full system boot and configurations were run
None

CASMTRIAGE-4452: Remove high priority from cfs session pods

---

src/cray/cfs/inventory/image/__init__.py

Fixes an issue when the new image map is not defined
* Resolves CASMCMS-8313
* Virtual Shasta
Successfully re-ran an image customization session that had been failing.
None

CASMCMS-8313: Fix image customizations for sessions without new imagemap

---

CHANGELOG.md
src/cray/cfs/operator/events/session_events.py

Authenticate to CSM's artifactory when using pip to access CSM's csm-python-modules.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves CASMINST-5443
* Tested by committing it to the build environment. There was not an artifactory available with the correct permissions to test against.
See above.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No.
- Were continuous integration tests run? If not, why? No.
- Was upgrade tested? If not, why? No.
- Was downgrade tested? If not, why? No.
- Were new tests (or test issues/Jiras) created for this change? No.
Low.

CASMINST-5443: Authenticate to CSM's artifactory

---

CHANGELOG.md
kubernetes/cray-cfs-operator/templates/configmap.yaml
kubernetes/cray-cfs-operator/values.yaml

Fixes an issue where half of the container limit change was pulled in when changes were made to collapse the Ansible layers.  This pulls in the remainder of the change.
* Resolves CASMCMS-8374
* Wasp
CFS sessions were successfully run
None

CASMCMS-8374: Fix container limits by including CASMCMS-8208

---

CHANGELOG.md
kubernetes/cray-cfs-operator/values.yaml
src/cray/cfs/operator/events/job_events.py
src/cray/cfs/operator/events/session_events.py

Addresses issues seen where the cfs-operator when down due memory limits and caused a backlog of session creation requests.  This both increases memory to prevent cfs-operator from exceeding this limit and improves recovery by ignoring old session creation requests.
* Resolves CASMCMS-8385
* Resolves CASMCMS-8384
* Mug
Tested downtime for the cfs-operator with and without the changes, and monitored the memory usage.
None

CASMCMS-8385: Fix issues around cfs-operator downtime

---

CHANGELOG.md
constraints.txt
src/cray/cfs/teardown/__main__.py

Builds in this repo are failing due to the problem documented in [CASMCMS-8713](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8713). Moving to PyYAML 6.0.1 resolves the problem. This PR moves PyYAML from 5.4.1 to 6.0.1.
A similar change is being made to a number of CSM repositories that are similarly affected.
This PR also includes a minor change to one source file, altering a `yaml.load()` function call to `yaml.safe_load()`. This would be a good change to make regardless, for security reasons, but the motivation to include it in this PR specifically is because one of the few breaking changes between PyYAML 5.4 and PyYAML 6 is that the `Loader` argument  to the `yaml.load()` function changed from optional to required, and the function call in this particular source file omits it.

CASMCMS-8713: Bump PyYAML from 5.4.1 to 6.0.1 to prevent build issue

---

CHANGELOG.md
Dockerfile
kubernetes/cray-cfs-operator/templates/configmap.yaml
kubernetes/cray-cfs-operator/values.yaml
requirements.txt
src/cray/cfs/clone/__init__.py
src/cray/cfs/clone/__main__.py
src/cray/cfs/clone/askpass.py
src/cray/cfs/operator/cfs/options.py
src/cray/cfs/operator/cfs/sources.py
src/cray/cfs/operator/events/session_events.py
src/cray/cfs/utils/__init__.py
src/cray/cfs/utils/kubernetes_utils.py
src/cray/cfs/utils/vault_utils.py
src/setup.py

Adds support for the new CFS "sources".  This allows users to specify repos, as well as their credentials and ca certs, so that CFS can access Ansible content outside the standard VCS.
Part of this change required switching the git-clone container to using the cfs-operator image so that credentials could be accessed securely.
* Resolves CASMCMS-8790
* Mug
- Tested updating, patching and deleting various sources.
- Tested adding configurations with branches, with and without sources (so the branch was converted in the API)
- Tested CFS sessions using configurations with and without sources.
None

CASMCMS-8790: Add support for cloning from sources

---

CHANGELOG.md
src/cray/cfs/utils/__init__.py

Fixes the code to apply configuration limits so that layer 0 is not missed when a config limit is specified.
* Resolves CASMTRIAGE-6195
* beau
Successfully ran a job that had previously been failing.
None

CASMTRIAGE-6195: Fix config limit for layer 0

---

CHANGELOG.md
src/cray/cfs/inventory/image/__init__.py

The inventory container was only waiting until the ssh connection was responding, not fully functional. This was leading to cases where it passes control to the ansible container, where ansible was assuming the connection was ready to go. In fact it was not ready, so would fail immediately. This does the deeper connection check at the inventory step so the ssh connection is ready when the ansible container starts to use it. 
* Resolves [CASMCMS-8896](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8896)
* `Mug`
I updated the new cfs-operator image into the CFS job config map and tested the remote jobs waiting for this connection to be fully functional
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests …

CASMCMS-8896 - update image inventory to authenticate ssh connection.

---

CHANGELOG.md
constraints.txt
kubernetes/cray-cfs-operator/Chart.yaml
kubernetes/cray-cfs-operator/values.yaml
update_versions.conf

This is a backport of https://github.com/Cray-HPE/cfs-operator/pull/121 for CSM 1.5.2

CASMCMS-9018: CASMCMS-9018: Bump paramiko version to avoid Blowfish deprecation warning

---

CHANGELOG.md
src/cray/cfs/operator/events/session_events.py

Currently, the CFS session TTL option only governs how long CFS keeps the record of the session in its database. It does not affect the TTL of the corresponding Kubernetes job. This PR modifies the behavior so that if the session_ttl option is set to a non-0 value, it will be used to specify the TTL of the Kubernetes job created by CFS.
This is to address the problem reported in [CASMTRIAGE-7163](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7163).
I have tested this on mug and verified that it works as expected.

CASMTRIAGE-7163: Use CFS session_ttl option when creating Kubernetes job

---

CHANGELOG.md
src/cray/cfs/operator/events/session_events.py

* [CASMTRIAGE-5890: Trim job labels that are too long](https://github.com/Cray-HPE/cfs-operator/commit/fae6eeabdbf164bcf76db6d148fab3cf72e21bf8)
* [CASMTRIAGE-7163: Use CFS session_ttl option when creating Kubernetes job](https://github.com/Cray-HPE/cfs-operator/commit/200f691aa8ca8a9690415dfb1d51bcfcf4e3247d)

CASMTRIAGE-5890/CASMTRIAGE-7163

---

CHANGELOG.md
update_external_versions.conf

cray-aee had its Docker image (and consequently its Python version) updated, since it was way back on SLES15 SP3 and was running into build issues. This PR updates cfs-operator to start using the updated cray-aee image.
I tested this on mug and verified that it works as expected.

CASMCMS-9115: Move to cray-aee 1.17

---

CHANGELOG.md
kubernetes/cray-cfs-operator/Chart.yaml

Update the cray-service chart version to the newest version to pick up changes needed for the updated k8s being deployed with csm 1.6.0.
* Resolves [CASMPET-7064](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7064)
* `Fanta`
Installed the new version via helm (along with updated cfs-batcher), ran through image customization and post-boot personalization workflows. Also ran the cmsdev CT tests before and after the upgrade. Everything worked as expected.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? N
Required to match the version of k8s …

CASMPET-7064 - update cray-service base chart.
